services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/drcrazykid/docker_data/qbittorrent/appdata:/config
      - /path/to/downloads:/downloads #optional
    ports:
      - 8083:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped