services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports: 8096:8096
    volumes: 
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - type: bind
        source: /mnt/jellyfinHDD
        target: /media
    restart: always

volumes:
  jellyfin-config:
  jellyfin-cache: